/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.wp2c2project;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jejer
 */
public class IndividualTimeCard extends javax.swing.JFrame {

    /**
     * Creates new form IndividualTimeCard
     */
    ResultSet resultSet;
    Connection sgconn = Main.connectSG();
    PreparedStatement st;

    int empId = 1;
    String empName;
    String dept;

    int dateId;
    String date;
    int dateType;
    String timeIn;
    String timeOut;
    String shiftStart;
    String shiftEnd;

    public IndividualTimeCard() {
        initComponents();

        try {
            st = (PreparedStatement) sgconn.prepareStatement("SELECT * FROM employee WHERE id = ?");
            st.setInt(1, empId);
            resultSet = st.executeQuery();
            resultSet.next();
            empName = resultSet.getString("name");
            dept = resultSet.getString("department");
            nameLabel.setText(empName);
            deptLabel.setText(dept);

            //add row to table
            st = (PreparedStatement) sgconn.prepareStatement("SELECT * FROM time_card WHERE empId = ?");
            st.setInt(1, empId);
            resultSet = st.executeQuery();
            while (resultSet.next()) {
                dateId = resultSet.getInt("dateId");
                date = resultSet.getString("date");
                dateType = resultSet.getInt("dateType");
                timeIn = resultSet.getString("timeIn");
                timeOut = resultSet.getString("timeOut");
                shiftStart = resultSet.getString("shiftStart");
                shiftEnd = resultSet.getString("shiftEnd");

                DefaultTableModel model = (DefaultTableModel) idvlTCTable.getModel();
                model.addRow(new Object[]{
                    dateId,
                    date,
                    shiftStart,
                    shiftEnd,
                    timeIn,
                    timeOut,
                    0, //day
                    0, //late
                    0, //ot
                    0, //nd
                    0, //spc hol/sun
                    0, //spc hol/sun ot
                    0, //leg hol          
                });
                System.out.println("getting dateId" + dateId + " success");
            }

        } catch (SQLException ex) {
            Logger.getLogger(IndividualTimeCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idvlTCTable = new javax.swing.JTable();
        periodLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        nameLabel.setText("Name");

        idvlTCTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        idvlTCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date ID", "Date", "Shift Start", "Shift End", "Time In", "Time Out", "Day", "Late", "Overtime", "Night Differential", "Special Holiday/Sunday", "Special Holiday/Sunday Overtime", "Legal Holiday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        idvlTCTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(idvlTCTable);

        periodLabel.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        periodLabel.setText("Date Period");

        deptLabel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        deptLabel.setText("Department");

        updateBtn.setText("Update");
        updateBtn.setToolTipText("");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(deptLabel)
                            .addComponent(periodLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateBtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(periodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptLabel)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
      
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualTimeCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel deptLabel;
    private javax.swing.JTable idvlTCTable;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JLabel periodLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
