/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.wp2c2project;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

interface SetupEmployeeCallback {

    void onSetupEmployeeFinished();
}

/**
 *
 * @author jejer
 */
public class SetupEmployee extends javax.swing.JFrame {

    /**
     * Creates new form registerEmployee
     */


    private String id = "0";
    private String name = "none";
    private String department = "none";

    public SetupEmployee(SummaryHome summaryHome) {
        initComponents();


        id = summaryHome.id;
        name = summaryHome.name;
        department = summaryHome.department;

        System.out.println(id + name + department);
        nameLabel.setText(name);
    }

    private SetupEmployeeCallback callback;

    public void setCallback(SetupEmployeeCallback callback) {
        this.callback = callback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rateField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tinField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        philHealthField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sssField = new javax.swing.JTextField();
        pagibigField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        taxStatusField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rateField1 = new javax.swing.JTextField();
        rateField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        nameLabel.setText("Name");

        jLabel2.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel2.setText("Rate");

        rateField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel1.setText("Enter details");

        jLabel3.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel3.setText("TIN");

        tinField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel4.setText("Phil Health No.");

        philHealthField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel5.setText("SSS No.");

        sssField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        sssField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssFieldActionPerformed(evt);
            }
        });

        pagibigField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel6.setText("Tax Status");

        taxStatusField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel7.setText("Pag-ibig No.");

        jButton1.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel8.setText("New employee found");

        jLabel9.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel9.setText("Shift start");

        jLabel10.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jLabel10.setText("Shift end");

        rateField1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        rateField1.setText("07:00");
        rateField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateField1ActionPerformed(evt);
            }
        });

        rateField2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        rateField2.setText("16:00");

        jButton2.setFont(new java.awt.Font("Inter Medium", 0, 12)); // NOI18N
        jButton2.setText("Skip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(nameLabel)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(philHealthField)
                    .addComponent(sssField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rateField)
                    .addComponent(tinField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(pagibigField)
                            .addComponent(taxStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(rateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rateField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(philHealthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sssField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rate = "0";
        String tin = "0";
        String philHealth = "0";
        String sss = "0";
        String pagibig = "0";
        String taxStatus = "none";

        if (!rateField.getText().isEmpty()) {
            rate = rateField.getText();
        }
        if (!tinField.getText().isEmpty()) {
            tin = tinField.getText();
        }
        if (!philHealthField.getText().isEmpty()) {
            philHealth = philHealthField.getText();
        }
        if (!sssField.getText().isEmpty()) {
            sss = sssField.getText();
        }
        if (!pagibigField.getText().isEmpty()) {
            pagibig = pagibigField.getText();
        }
        if (!taxStatusField.getText().isEmpty()) {
            taxStatus = taxStatusField.getText();
        }

        Connection sgconn = SynergyGrafix.connectSG();
        PreparedStatement st;
        try {
            st = (PreparedStatement) sgconn.prepareStatement("INSERT INTO `employee`(`id`, `name`, `department`, `rate`, `tin`, `philHealth`, `sss`, `pagibig`, `taxStatus`) VALUES (?,?,?,?,?,?,?,?,?)");
            st.setString(1, id);
            st.setString(2, name);
            st.setString(3, department);
            st.setString(4, rate);
            st.setString(5, tin);
            st.setString(6, philHealth);
            st.setString(7, sss);
            st.setString(8, pagibig);
            st.setString(9, taxStatus);
            st.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(SetupEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (callback != null) {
            callback.onSetupEmployeeFinished();
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sssFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sssFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rateField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SummaryHome summaryHome = new SummaryHome();
                new SetupEmployee(summaryHome).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JTextField pagibigField;
    public javax.swing.JTextField philHealthField;
    public javax.swing.JTextField rateField;
    public javax.swing.JTextField rateField1;
    public javax.swing.JTextField rateField2;
    public javax.swing.JTextField sssField;
    public javax.swing.JTextField taxStatusField;
    public javax.swing.JTextField tinField;
    // End of variables declaration//GEN-END:variables
}
